parameters:
     locale: pl
     app:
         week_price: 9
         currency: zł
         phone_prefix: '+48'
         demo_period_days: 2
         expiration_hour: 23:30
         measures:
             good: [["sztuka", "szt."], ["metr", "m"], ["metr bieżący", "m b."], ["kilogram", "kg"], ["litr", "l"], ["opakowanie", "opak."], ["komplet", "kpl."]]
             service: [["roboczogodzina", "rg."]]
         default_good_measure: "sztuka"
         provinces: ["dolnośląskie", "kujawsko-pomorskie", "lubelskie", "lubuskie", "łódzkie", "małopolskie", "mazowieckie", "opolskie", "podkarpackie", "podlaskie", "pomorskie", "śląskie", "świętokrzyskie", "warmińsko-mazurskie", "wielkopolskie", "zachodniopomorskie"]
         engine_types: ["benzyna", "benzyna + gaz", "diesel", "hybryda", "ee"]
         statuses: [["przyjęte", "#00ff00"],  ["diagnoza", "#3399ff"], ["oczekuje na części", "#993333" ], ["w toku", "#006600"], ["odłożone", "#9999ff" ], ["przerwa", "#ff0066" ], ["naprawione", "#ffff00"]]
         actions: ["wymiana", "zmiana", "przegląd", "regulacja", "naprawa", "montaż", "demontaż", "usunięcie", "sprawdzenie", "robocizna", "spawanie", "lutowanie", "uszczelnienie", "programowanie", "ustawienie", "regeneracja", "wyczyszczenie", "dezynfekcja"]
         workstations: ['stanowisko naprawcze 1', 'stanowisko naprawcze 2']
         positions: ['administrator aplikacji', 'mechanik']
         limit_set: [15, 30, 70, 125, 200]
         default_limit: 15
         warehouse_documents: ["invoice", "voucher", "issue"]
