app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /

header:
    resource: "@HeaderBundle/Resources/config/routing.yml"
    prefix: /header

customer:
    resource: '@CustomerBundle/Resources/config/routing.yml'
    prefix: /

vehicle:
    resource: "@VehicleBundle/Resources/config/routing.yml"
    prefix: /

order:
    resource: "@OrderBundle/Resources/config/routing.yml"
    prefix: /

delivery:
    resource: "@DeliveryBundle/Resources/config/routing.yml"
    prefix: /

sale:
    resource: "@SaleBundle/Resources/config/routing.yml"
    prefix: /

warehouse:
    resource: "@WarehouseBundle/Resources/config/routing.yml"
    prefix: /

service:
    resource: "@ServiceBundle/Resources/config/routing.yml"
    prefix: /

invoice:
    resource: "@InvoiceBundle/Resources/config/routing.yml"
    prefix: /

storage:
    resource: "@StorageBundle/Resources/config/routing.yml"
    prefix: /

sms:
    resource: "@SmsBundle/Resources/config/routing.yml"
    prefix: /

email:
    resource: "@EmailBundle/Resources/config/routing.yml"
    prefix: /

workflow:
    resource: "@WorkflowBundle/Resources/config/routing.yml"
    prefix: /

trash:
    resource: "@TrashBundle/Resources/config/routing.yml"
    prefix: /


