# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 13

    role_hierarchy:
        ROLE_DEVELOPER: [ROLE_USER]
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

        my_provider:
            entity:
                class: AppBundle\Entity\User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            provider: my_provider
            simple_form:
                authenticator: app.security.user_authenticator
                login_path: app_login
                check_path: app_login
                default_target_path: customer_index
                always_use_default_target_path: true
                username_parameter: login[user][email]
                password_parameter: login[user][password]
                use_forward: false
            logout:
                path: /wyloguj
                target: /logowanie

    access_control:
     #   - { path: ^/logowanie, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      #  - { path: ^/rejestracja, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         # - { path: ^/, roles: ROLE_USER }
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
