# DELIVERY
delivery_index:
    path: /przyjecia-towarow
    defaults: { _controller: DeliveryBundle:Delivery:index }
    
delivery_retrieve:
    path: /delivery-retrieve
    defaults: { _controller: DeliveryBundle:Delivery:retrieve }

delivery_show:
    path: /przyjecie-towaru/{deliveryHeaderId}
    defaults: { _controller: DeliveryBundle:Delivery:show }

# HEADER
delivery_header_add:
    path: /przyjmij-towar
    defaults: { _controller: DeliveryBundle:DeliveryHeader:add }

delivery_header_retrieve_customers:
    path: /delivery/retrieve-customers
    defaults: { _controller: DeliveryBundle:DeliveryHeader:retrieveCustomers }

# DETAIL
delivery_detail_add:
    path: /przyjecie-towaru/{deliveryHeaderId}/dodaj-pozycje
    defaults: { _controller: DeliveryBundle:DeliveryDetail:add }