delivery_index:
    path: /przyjecia-towarow
    defaults: { _controller: DeliveryBundle:Delivery:index }
    
delivery_retrieve:
    path: /delivery-retrieve
    defaults: { _controller: DeliveryBundle:Delivery:retrieve }

delivery_show:
    path: /przyjecia-towarow/{deliveryHeaderId}
    defaults: { _controller: DeliveryBundle:Delivery:show }

delivery_header_add:
    path: /przyjmij-towar
    defaults: { _controller: DeliveryBundle:DeliveryHeader:add }

delivery_header_retrieve_customers:
    path: /delivery/retrieve-customers
    defaults: { _controller: DeliveryBundle:DeliveryHeader:retrieveCustomers }
