services:
# FORM TYPES
  form.type.delivery_header_add:
      class: DeliveryBundle\Form\DeliveryHeaderAddType
      tags:
          - { name: form.type }

  form.type.delivery_detail_add:
      class: DeliveryBundle\Form\DeliveryDetailAddType
      arguments: ["@security.token_storage"]
      tags:
          - { name: form.type }

# SERVICES

  delivery.helper.header_add:
      class: DeliveryBundle\Service\Helper\DeliveryHeaderAddHelper
      arguments: ["@security.token_storage", "@request_stack", "@doctrine.orm.default_entity_manager", "@form.factory", "@customer.helper.index", "@customer.helper.add", "@app.trade"]

  delivery.helper.index:
      class: DeliveryBundle\Service\Helper\DeliveryIndexHelper
      arguments: ["@request_stack", "@security.token_storage", "@form.factory", "@doctrine.orm.default_entity_manager", "@service_container"]

  delivery.helper.show:
      class: DeliveryBundle\Service\Helper\DeliveryShowHelper
      arguments: ["@request_stack", "@security.token_storage", "@doctrine.orm.entity_manager"]

  delivery.helper.detail_add:
      class: DeliveryBundle\Service\Helper\DeliveryDetailAddHelper
      arguments: ["@request_stack", "@security.token_storage", "@doctrine.orm.entity_manager", "@form.factory", "@warehouse.helper.good", "@warehouse.helper.indexx", "@app.trade"]