services:
# FORM TYPES
  form.type.delivery_header_add:
      class: DeliveryBundle\Form\DeliveryHeaderAddType
      tags:
          - { name: form.type }
# SERVICES

  delivery.helper.header_add:
      class: DeliveryBundle\Service\Helper\DeliveryHeaderAddHelper
      arguments: ["@security.token_storage", "@request_stack", "@doctrine.orm.default_entity_manager", "@form.factory", "@customer.helper.index", "@customer.helper.add", "@app.trade"]
