<?php

namespace AppBundle\Entity\Repository;
use Doctrine\ORM\Query;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOne($id, $hydrationMode = Query::HYDRATE_OBJECT)
    {
        $address = $this->_em
            ->createQueryBuilder()
            ->select('a')
            ->from('AppBundle:Address', 'a')
            ->where('a.id = :id')
            ->setParameter(':id', $id)
            ->getQuery()
            ->getOneOrNullResult($hydrationMode)
            ;

        return $address;
    }
}
