<?php

namespace AppBundle\Entity\Repository;
use AppBundle\Entity\Workshop;

/**
 * CarBrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarBrandRepository extends \Doctrine\ORM\EntityRepository
{

    public function getOne(Workshop $workshop, $id)
    {
        $carBrand = $this->_em->createQueryBuilder()
            ->select('c')
            ->from('AppBundle:CarBrand', 'c')
            ->where('c.removed_at IS NULL')
            ->andWhere('c.deleted_at IS NULL')
            ->andWhere('c.workshop = :workshop')
            ->andWhere('c.id = :id')
            ->setParameters([
                ':workshop' => $workshop,
                ':id'       => $id,
            ])
            ->getQuery()
            ->getOneOrNullResult()
        ;

        return $carBrand;
    }

    public function retrieve(Workshop $workshop)
    {
        $carBrands = $this->_em->createQueryBuilder()
            ->select('c')
            ->from('AppBundle:CarBrand', 'c')
            ->where('c.removed_at IS NULL')
            ->andWhere('c.deleted_at IS NULL')
            ->andWhere('c.workshop = :workshop')
            ->setParameters([
                ':workshop' => $workshop,
            ])
            ->getQuery()
            ->getResult()
            ;

        return $carBrands;
    }


    public function getOneByName(Workshop $workshop, $name)
    {
        $carBrand = $this->_em->createQueryBuilder()
            ->select('c')
            ->from('AppBundle:CarBrand', 'c')
            ->where('c.removed_at IS NULL')
            ->andWhere('c.deleted_at IS NULL')
            ->andWhere('c.workshop = :workshop')
            ->andWhere('c.name = :name')
            ->setParameters([
                ':workshop' => $workshop,
                ':name'     => $name,
            ])
            ->getQuery()
            ->getOneOrNullResult()
        ;

        return $carBrand;
    }

    public function getOneRemovedByName(Workshop $workshop, $name)
    {
        $carBrand = $this->_em->createQueryBuilder()
            ->select('c')
            ->from('AppBundle:CarBrand', 'c')
            ->where('c.removed_at IS NOT NULL OR c.deleted_at IS NOT NULL')
            ->andWhere('c.workshop = :workshop')
            ->andWhere('c.name = :name')
            ->setParameters([
                ':workshop' => $workshop,
                ':name'     => $name,
            ])
            ->getQuery()
            ->getOneOrNullResult()
        ;

        return $carBrand;
    }

    public function getOthersSimilar(Workshop $workshop, $name, $id)
    {
        $carBrands = $this->_em->createQueryBuilder()
            ->select('c')
            ->from('AppBundle:CarBrand', 'c')
            ->where('c.workshop = :workshop')
            ->andWhere('c.removed_at IS NULL OR c.deleted_at IS NULL')
            ->andWhere('c.name = :name')
            ->andWhere('c.id != :id')
            ->setParameters([
                ':workshop' => $workshop,
                ':name'     => $name,
                ':id'       => $id,
            ])
            ->getQuery()
            ->getResult()
        ;

        return $carBrands;
    }
}
