<?php

namespace AppBundle\Entity\Repository;
use AppBundle\Entity\Workshop;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOne(Workshop $workshop, $id)
    {
        $category = $this->_em->createQueryBuilder()
            ->select('c')
            ->from('AppBundle:Category', 'c')
            ->where('c.removed_at IS NULL')
            ->andWhere('c.deleted_at IS NULL')
            ->andWhere('c.workshop = :workshop')
            ->andWhere('c.id = :id')
            ->setParameters([
                ':workshop' => $workshop,
                ':id'       => $id,
            ])
            ->getQuery()
            ->getOneOrNullResult()
        ;

        return $category;
    }

    public function retrieve(Workshop $workshop)
    {
        $categories = $this->_em->createQueryBuilder()
            ->select('c')
            ->from('AppBundle:Category', 'c')
            ->where('c.removed_at IS NULL')
            ->andWhere('c.deleted_at IS NULL')
            ->andWhere('c.workshop = :workshop')
            ->setParameters([
                ':workshop' => $workshop,
            ])
            ->getQuery()
            ->getResult()
        ;

        return $categories;
    }

    public function retrieveByGoodId(Workshop $workshop, $goodIds = [])
    {
        $categories = $this->_em->createQueryBuilder()
            ->select('c')
            ->from('AppBundle:Category', 'c')
            ->innerJoin('c.goods', 'g')
            ->where('c.removed_at IS NULL')
            ->andWhere('c.deleted_at IS NULL')
            ->andWhere('c.workshop = :workshop')
            ->andWhere('g.id IN (:goodIds)')
            ->setParameters([
                ':workshop' => $workshop,
                ':goodIds' => $goodIds,
            ])
            ->getQuery()
            ->getResult()
        ;

        return $categories;
    }


    public function getOneByName(Workshop $workshop, $name)
    {
        $category = $this->_em->createQueryBuilder()
            ->select('c')
            ->from('AppBundle:Category', 'c')
            ->where('c.removed_at IS NULL')
            ->andWhere('c.deleted_at IS NULL')
            ->andWhere('c.workshop = :workshop')
            ->andWhere('c.name = :name')
            ->setParameters([
                ':workshop' => $workshop,
                ':name'     => $name,
            ])
            ->getQuery()
            ->getOneOrNullResult()
        ;

        return $category;
    }

    public function getOneRemovedByName(Workshop $workshop, $name)
    {
        $category = $this->_em->createQueryBuilder()
            ->select('c')
            ->from('AppBundle:Category', 'c')
            ->where('c.removed_at IS NOT NULL OR c.deleted_at IS NOT NULL')
            ->andWhere('c.workshop = :workshop')
            ->andWhere('c.name = :name')
            ->setParameters([
                ':workshop' => $workshop,
                ':name'     => $name,
            ])
            ->getQuery()
            ->getOneOrNullResult()
        ;

        return $category;
    }
}
