<?php

namespace AppBundle\Entity\Repository;
use AppBundle\Entity\Good;
use AppBundle\Entity\Indexx;
use AppBundle\Entity\Workshop;

/**
 * DeliveryDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryDetailRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByIndexx(Workshop $workshop, Indexx $indexx)
    {
        $deliveryDetails = $this->_em->createQueryBuilder()
            ->select('d')
            ->from('AppBundle:DeliveryDetail', 'd')
            ->innerJoin('AppBundle:DeliveryHeader', 'h', 'WITH', 'd.delivery_header_id = h.id')
            ->where('d.removed_at IS NULL')
            ->andWhere('d.removed_at IS NULL')
            ->andWhere('h.removed_at IS NULL')
            ->andWhere('h.deleted_at IS NULL')
            ->andWhere('h.workshop = :workshop')
            ->andWhere('d.indexx = :indexx')
            ->setParameters([
                ':workshop' => $workshop,
                ':indexx' => $indexx,
            ])
            ->orderBy('d.updated_at', 'DESC')
            ->getQuery()
            ->getResult()
        ;

        return $deliveryDetails;
    }

    public function getByGood(Workshop $workshop, Good $good)
    {
        $deliveryDetails = $this->_em->createQueryBuilder()
            ->select('d')
            ->from('AppBundle:DeliveryDetail', 'd')
            ->innerJoin('AppBundle:DeliveryHeader', 'h', 'WITH', 'd.delivery_header_id = h.id')
            ->innerJoin('AppBundle:Indexx', 'i', 'WITH', 'd.indexx_id = i.id')
            ->innerJoin('AppBundle:Good', 'g', 'WITH', 'i.good_id = g.id')
            ->where('d.removed_at IS NULL')
            ->andWhere('d.removed_at IS NULL')
            ->andWhere('h.removed_at IS NULL')
            ->andWhere('h.deleted_at IS NULL')
            ->andWhere('i.removed_at IS NULL')
            ->andWhere('i.deleted_at IS NULL')
            ->andWhere('h.workshop = :workshop')
            ->andWhere('i.good = :good')
            ->setParameters([
                ':workshop' => $workshop,
                ':good' => $good,
            ])
            ->orderBy('d.updated_at', 'DESC')
            ->getQuery()
            ->getResult()
        ;

        return $deliveryDetails;
    }
}
