<?php

namespace AppBundle\Entity\Repository;

/**
 * DeliveryHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryHeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
