<?php

namespace AppBundle\Entity\Repository;

/**
 * DeliveryDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
