<?php

namespace AppBundle\Entity\Repository;
use AppBundle\Entity\Workshop;
use Doctrine\ORM\Query;

/**
 * GoodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOne(Workshop $workshop, $id, $hydrationMode = Query::HYDRATE_OBJECT)
    {
        $good = $this->_em
            ->createQueryBuilder()
            ->select('g')
            ->from('AppBundle:Good', 'g')
            ->where('g.deleted_at IS NULL')
            ->andWhere('g.removed_at IS NULL')
            ->andWhere('g.workshop = :workshop')
            ->andWhere('g.id = :id')
            ->setParameters([
                ':workshop' => $workshop,
                ':id'       => $id,
            ])
            ->getQuery()
            ->getOneOrNullResult($hydrationMode)
        ;

        return $good;
    }

    public function retrieve(Workshop $workshop, $sortableParameters = [])
    {
        $search     = $sortableParameters['search'];
        $limit      = (int) $sortableParameters['limit'];
        $offset     = (int) $sortableParameters['offset'];
        $sortOrder  = $sortableParameters['sortOrder'];
        $sortColumnName     = $sortableParameters['sortColumnName'];
        $filterCategoryIds  = $sortableParameters['filterCategoryIds'];
        $filterModelIds     = $sortableParameters['filterModelIds'];
        $filterIndexxIds     = $sortableParameters['filterIndexxIds'];

        $queryBuilder = $this->_em
            ->createQueryBuilder()
            ->select('g')
            ->from('AppBundle:Good', 'g')
            ->leftJoin('AppBundle:Indexx', 'i', 'WITH', 'i.good_id = g.id')
            ->leftJoin('AppBundle:Measure', 'm', 'WITH', 'g.measure_id = m.id')
            ->leftJoin('AppBundle:Producer', 'p', 'WITH', 'i.producer_id = p.id')
            ->leftJoin('g.car_models', 'cm')
            ->leftJoin('cm.brand', 'cb', 'WITH', 'cm.brand_id = cb.id')
        ;

        if(count($filterCategoryIds) > 0)
        {
            $queryBuilder
                ->innerJoin('g.categories', 'c')
                ->where('c.id IN (:filterCategoryIds)')
                ->andWhere('c.deleted_at IS NULL')
                ->andWhere('c.removed_at IS NULL')
                ->setParameter(':filterCategoryIds', $filterCategoryIds)
            ;
        }

        if(count($filterModelIds) > 0)
        {
            $queryBuilder
                ->innerJoin('g.car_models', 'model')
                ->where('model.id IN (:filterModelIds)')
                ->andWhere('model.deleted_at IS NULL')
                ->andWhere('model.removed_at IS NULL')
                ->setParameter(':filterModelIds', $filterModelIds)
            ;
        }

        if(count($filterIndexxIds) > 0)
        {
            $queryBuilder
                ->innerJoin('g.indexxes', 'indexx')
                ->where('indexx.id IN (:filterIndexxIds)')
                ->andWhere('indexx.deleted_at IS NULL')
                ->andWhere('indexx.removed_at IS NULL')
                ->setParameter(':filterIndexxIds', $filterIndexxIds)
            ;
        }

        $goods = $queryBuilder
            ->andWhere('g.workshop = :workshop')
            ->andWhere('g.deleted_at IS NULL')
            ->andWhere('g.removed_at IS NULL')
            ->andWhere('i.removed_at IS NULL')
            ->andWhere('i.deleted_at IS NULL')
            ->andWhere("
                    g.name LIKE :search
                OR  g.remarks LIKE :search
                OR  m.name LIKE :search
                OR  m.shortcut LIKE :search
                OR  i.name LIKE :search
                OR  p.name LIKE :search
                OR  CONCAT_WS(' ', cm.name, cb.name) LIKE :search
            ")
            ->orderBy($sortColumnName, $sortOrder)
            ->addOrderBy('g.updated_at', 'DESC')
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->groupBy('g.id')
            ->setParameter(':workshop', $workshop)
            ->setParameter(':search', '%' . $search . '%')
            ->getQuery()
            ->getResult()
        ;

        return $goods;
    }

    public function getCountAllRetrieved(Workshop $workshop, $sortableParameters = [])
    {
        $search     = $sortableParameters['search'];
        $sortOrder  = $sortableParameters['sortOrder'];
        $sortColumnName = $sortableParameters['sortColumnName'];
        $filterCategoryIds  = $sortableParameters['filterCategoryIds'];
        $filterModelIds     = $sortableParameters['filterModelIds'];
        $filterIndexxIds     = $sortableParameters['filterIndexxIds'];

        $queryBuilder = $this->_em
            ->createQueryBuilder()
            ->select('COUNT(g)')
            ->from('AppBundle:Good', 'g')
            ->leftJoin('AppBundle:Indexx', 'i', 'WITH', 'i.good_id = g.id')
            ->leftJoin('AppBundle:Measure', 'm', 'WITH', 'g.measure_id = m.id')
            ->leftJoin('AppBundle:Producer', 'p', 'WITH', 'i.producer_id = p.id')
            ->leftJoin('g.car_models', 'cm')
            ->leftJoin('cm.brand', 'cb', 'WITH', 'cm.brand_id = cb.id')
        ;

        if(count($filterCategoryIds) > 0)
        {
            $queryBuilder
                ->innerJoin('g.categories', 'c')
                ->where('c.id IN (:filterCategoryIds)')
                ->andWhere('c.deleted_at IS NULL')
                ->andWhere('c.removed_at IS NULL')
                ->setParameter(':filterCategoryIds', $filterCategoryIds)
            ;
        }

        if(count($filterModelIds) > 0)
        {
            $queryBuilder
                ->innerJoin('g.car_models', 'model')
                ->where('model.id IN (:filterModelIds)')
                ->andWhere('model.deleted_at IS NULL')
                ->andWhere('model.removed_at IS NULL')
                ->setParameter(':filterModelIds', $filterModelIds)
            ;
        }

        if(count($filterIndexxIds) > 0)
        {
            $queryBuilder
                ->innerJoin('g.indexxes', 'indexx')
                ->where('indexx.id IN (:filterIndexxIds)')
                ->andWhere('indexx.deleted_at IS NULL')
                ->andWhere('indexx.removed_at IS NULL')
                ->setParameter(':filterIndexxIds', $filterIndexxIds)
            ;
        }

        $countGoods = $queryBuilder
            ->andWhere('g.workshop = :workshop')
            ->andWhere('g.deleted_at IS NULL')
            ->andWhere('g.removed_at IS NULL')
            ->andWhere('i.removed_at IS NULL')
            ->andWhere('i.deleted_at IS NULL')
            ->andWhere("
                    g.name LIKE :search
                OR  g.remarks LIKE :search
                OR  m.name LIKE :search
                OR  m.shortcut LIKE :search
                OR  i.name LIKE :search
                OR  p.name LIKE :search
                OR  CONCAT_WS(' ', cm.name, cb.name) LIKE :search
            ")
            ->orderBy($sortColumnName, $sortOrder)
            ->addOrderBy('g.updated_at', 'DESC')
            ->setParameter(':workshop', $workshop)
            ->setParameter(':search', '%' . $search . '%')
            ->getQuery()
            ->getSingleScalarResult()
        ;

        return $countGoods;
    }
}
