<?php

namespace AppBundle\Entity\Repository;

/**
 * IndexxEditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndexxEditRepository extends \Doctrine\ORM\EntityRepository
{
}
