<?php

namespace AppBundle\Entity\Repository;

/**
 * IndexxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndexxRepository extends \Doctrine\ORM\EntityRepository
{
}
