<?php

namespace AppBundle\Entity\Repository;
use AppBundle\Entity\Workshop;

/**
 * OrderHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderHeaderRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCountMonthly(Workshop $workshop)
    {
        $count = $this->_em->createQueryBuilder()
            ->select('COUNT(o)')
            ->from('AppBundle:OrderHeader', 'o')
            ->where('o.workshop = :workshop')
            ->andWhere('o.removed_at IS NULL')
            ->andWhere('o.deleted_at IS NULL')
            ->andWhere('MONTH(o.created_at) = :month')
            ->setParameters([
                ':workshop' => $workshop,
                ':month' => date('m')
            ])
            ->getQuery()
            ->getSingleScalarResult()
        ;

        return $count;
    }

    public function getCountYearly(Workshop $workshop)
    {
        $count = $this->_em->createQueryBuilder()
            ->select('COUNT(o)')
            ->from('AppBundle:OrderHeader', 'o')
            ->where('o.workshop = :workshop')
            ->andWhere('o.removed_at IS NULL')
            ->andWhere('o.deleted_at IS NULL')
            ->andWhere('YEAR(o.created_at) = :year')
            ->setParameters([
                ':workshop' => $workshop,
                ':year' => date('Y')
            ])
            ->getQuery()
            ->getSingleScalarResult()
        ;

        return $count;
    }

}
