<?php

namespace AppBundle\Entity\Repository;

/**
 * OrderIndexxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderIndexxRepository extends \Doctrine\ORM\EntityRepository
{
}
