<?php

namespace AppBundle\Entity\Repository;
use AppBundle\Entity\Workshop;

/**
 * OrderSymptomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderSymptomRepository extends \Doctrine\ORM\EntityRepository
{
    public function retrieveNames(Workshop $workshop)
    {
        $symptomNames = $this->_em->createQueryBuilder()
            ->select('s.name')
            ->from('AppBundle:OrderSymptom', 's')
            ->leftJoin('AppBundle:OrderHeader', 'h', 'WITH', 's.order_header_id = h.id')
            ->where('h.workshop = :workshop')
            ->andWhere('s.deleted_at IS NULL')
            ->andWhere('s.removed_at IS NULL')
            ->andWhere('h.removed_at IS NULL')
            ->andWhere('h.deleted_at IS NULL')
            ->setParameter(':workshop', $workshop)
            ->orderBy('s.name', 'ASC')
            ->getQuery()
            ->getArrayResult()
            ;

        return $symptomNames;
    }

    public function retrieve(Workshop $workshop)
    {
        $symptoms = $this->_em->createQueryBuilder()
            ->select('s.name')
            ->from('AppBundle:OrderSymptom', 's')
            ->leftJoin('AppBundle:OrderHeader', 'h', 'WITH', 's.order_header_id = h.id')
            ->where('h.workshop = :workshop')
            ->andWhere('s.deleted_at IS NULL')
            ->andWhere('s.removed_at IS NULL')
            ->andWhere('h.removed_at IS NULL')
            ->andWhere('h.deleted_at IS NULL')
            ->setParameter(':workshop', $workshop)
            ->orderBy('s.name', 'ASC')
            ->distinct()
            ->getQuery()
            ->getResult()
        ;

        return $symptoms;
    }



}
