<?php

namespace AppBundle\Entity\Repository;

/**
 * OrderServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
