<?php

namespace AppBundle\Entity\Repository;

/**
 * OrderSymptomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderSymptomRepository extends \Doctrine\ORM\EntityRepository
{
}
