<?php

namespace AppBundle\Entity\Repository;

/**
 * OrderFaultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderFaultRepository extends \Doctrine\ORM\EntityRepository
{
}
