<?php

namespace AppBundle\Entity\Repository;
use AppBundle\Entity\Workshop;

/**
 * PositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOne(Workshop $workshop, $id)
    {
        $position = $this->_em->createQueryBuilder()
            ->select('p')
            ->from('AppBundle:Position', 'p')
            ->where('p.removed_at IS NULL')
            ->andWhere('p.deleted_at IS NULL')
            ->andWhere('p.workshop = :workshop')
            ->andWhere('p.id = :id')
            ->setParameters([
                ':workshop' => $workshop,
                ':id'       => $id,
            ])
            ->getQuery()
            ->getOneOrNullResult()
        ;

        return $position;
    }

    public function retrieve(Workshop $workshop)
    {
        $positions = $this->_em->createQueryBuilder()
            ->select('p')
            ->from('AppBundle:Position', 'p')
            ->where('p.removed_at IS NULL')
            ->andWhere('p.deleted_at IS NULL')
            ->andWhere('p.workshop = :workshop')
            ->setParameters([
                ':workshop' => $workshop,
            ])
            ->getQuery()
            ->getResult()
        ;

        return $positions;
    }

    public function getOneByName(Workshop $workshop, $name)
    {
        $position = $this->_em->createQueryBuilder()
            ->select('p')
            ->from('AppBundle:Position', 'p')
            ->where('p.removed_at IS NULL')
            ->andWhere('p.deleted_at IS NULL')
            ->andWhere('p.workshop = :workshop')
            ->andWhere('p.name = :name')
            ->setParameters([
                ':workshop' => $workshop,
                ':name'     => $name,
            ])
            ->getQuery()
            ->getOneOrNullResult()
        ;

        return $position;
    }

    public function getOneRemovedByName(Workshop $workshop, $name)
    {
        $position = $this->_em->createQueryBuilder()
            ->select('p')
            ->from('AppBundle:Position', 'p')
            ->where('p.removed_at IS NOT NULL OR p.deleted_at IS NOT NULL')
            ->andWhere('p.workshop = :workshop')
            ->andWhere('p.name = :name')
            ->setParameters([
                ':workshop' => $workshop,
                ':name'     => $name,
            ])
            ->getQuery()
            ->getOneOrNullResult()
        ;

        return $position;
    }
}
