<?php

namespace AppBundle\Entity\Repository;

/**
 * SaleHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleHeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
