<?php

namespace AppBundle\Entity\Repository;

/**
 * SaleDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
