<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\User;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository implements UserProviderInterface, UserLoaderInterface
{

    public function loadUserByUsername($username)
    {
        return $this->createQueryBuilder('u')
            ->where('u.mobile_phone = :mobile_phone OR u.email = :email')
            ->setParameter(':mobile_phone', $username)
            ->setParameter(':email', $username)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function refreshUser(UserInterface $user)
    {
        if(!$user instanceof User)
        {
            throw new UnsupportedUserException('Instances of "%s" are not supported.' . get_class($user));
        }
    }

    public function supportsClass($class)
    {
        return User::class;
    }

}
