<?php

namespace AppBundle\Entity\Repository;

/**
 * UserRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
