<?php

namespace AppBundle\Entity\Repository;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository implements UserLoaderInterface
{

    public function loadUserByUsername($username)
    {
        $user = $this->createQueryBuilder('u')
            ->where('u.mobile_phone = :mobile_phone OR u.email = :email')
            ->setParameter(':mobile_phone', $username)
            ->setParameter(':email', $username)
            ->getQuery()
            ->getOneOrNullResult();

        return $user;
    }

}
