<?php

namespace AppBundle\Entity\Repository;

/**
 * WorkshopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkshopRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOne($id)
    {
        $workshop = $this->_em->createQueryBuilder()
            ->select('w')
            ->from('AppBundle:Workshop', 'w')
            ->where('w.removed_at IS NULL')
            ->andWhere('w.deleted_at IS NULL')
            ->andWhere('w.id = :id')
            ->setParameters([
                ':id' => $id,
            ])
            ->getQuery()
            ->getOneOrNullResult()
            ;

        return $workshop;
    }

}
