<?php

namespace AppBundle\Entity\Repository;

/**
 * WorkmanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkmanRepository extends \Doctrine\ORM\EntityRepository
{
}
