<?php

namespace AppBundle\Entity\Repository;

/**
 * WorkstationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkstationRepository extends \Doctrine\ORM\EntityRepository
{
}
