warehouse_good_index:
    path: /towary
    defaults: { _controller: WarehouseBundle:Warehouse:index }

warehouse_producer_index:
    path: /producenci-towarow
    defaults: { _controller: WarehouseBundle:Producer:index }