warehouse_good_index:
    path: /towary
    defaults: { _controller: WarehouseBundle:Warehouse:index }

warehouse_good_show:
    path: /towary/{goodId}
    defaults: { _controller: WarehouseBundle:Warehouse:show }

warehouse_producer_index:
    path: /producenci-towarow
    defaults: { _controller: WarehouseBundle:Producer:index }

warehouse_producer_add:
    path: /producer-add
    defaults: { _controller: WarehouseBundle:Producer:add }

warehouse_producer_edit:
    path: /producer-edit
    defaults: { _controller: WarehouseBundle:Producer:edit }

warehouse_producer_remove:
    path: /producer-remove
    defaults: { _controller: WarehouseBundle:Producer:remove }

warehouse_category_get_selectable_modal:
    path: /warehouse/category/get-selectable-modal
    defaults: { _controller: WarehouseBundle:Category:getSelectableModal }