warehouse_good_index:
    path: /towary
    defaults: { _controller: WarehouseBundle:Warehouse:index }

warehouse_good_show:
    path: /towary/{goodId}
    defaults: { _controller: WarehouseBundle:Warehouse:show }

warehouse_producer_index:
    path: /producenci-towarow
    defaults: { _controller: WarehouseBundle:Producer:index }

warehouse_producer_add:
    path: /producer-add
    defaults: { _controller: WarehouseBundle:Producer:add }

warehouse_producer_edit:
    path: /producer-edit
    defaults: { _controller: WarehouseBundle:Producer:edit }

warehouse_producer_remove:
    path: /producer-remove
    defaults: { _controller: WarehouseBundle:Producer:remove }

warehouse_selectable_get_categories:
    path: /warehouse/selectable/get-categories
    defaults: { _controller: WarehouseBundle:Ajax:getSelectableCategories }

warehouse_selectable_get_models:
    path: /warehouse/selectable/get-models
    defaults: { _controller: WarehouseBundle:Ajax:getSelectableModels }

warehouse_get_one_good:
    path: /warehouse/get-one-good
    defaults: { _controller: WarehouseBundle:Ajax:getOneGood }

warehouse_get_one_indexx:
    path: /warehouse/get-one-indexx
    defaults: { _controller: WarehouseBundle:Ajax:getOneIndexx }

