services:
# FORM TYPES
    form.type.good:
        class: WarehouseBundle\Form\GoodType
        tags:
            - { name: form.type }

    form.type.indexx:
        class: WarehouseBundle\Form\IndexxType
        tags:
            - { name: form.type }

# HELPERS
    warehouse.helper.producer:
        class: WarehouseBundle\Service\Helper\ProducerHelper
        arguments: ["@doctrine.orm.default_entity_manager", "@request_stack", "@security.token_storage"]


    warehouse.helper.good:
        class: WarehouseBundle\Service\Helper\GoodHelper
        arguments: ["@request_stack", "@security.token_storage", "@doctrine.orm.default_entity_manager", "@service_container"]

    warehouse.helper.indexx:
            class: WarehouseBundle\Service\Helper\IndexxHelper
            arguments: ["@request_stack", "@security.token_storage", "@doctrine.orm.default_entity_manager", "@service_container"]

    warehouse.helper.good_show:
        class: WarehouseBundle\Service\Helper\GoodShowHelper
        arguments: ["@request_stack", "@security.token_storage", "@doctrine.orm.default_entity_manager"]