header_user_edit:
    path: /user-edit
    defaults: { _controller: HeaderBundle:User:edit }

header_password_change:
    path: /password-change
    defaults: { _controller: HeaderBundle:Password:change }

header_workshop_index:
    path: /workshop-index
    defaults: { _controller: HeaderBundle:Workshop:index }

header_workshop_add:
    path: /workshop-add
    defaults: { _controller: HeaderBundle:Workshop:add }

header_workshop_switch:
    path: /workshop-switch
    defaults: { _controller: HeaderBundle:Workshop:switch }

header_workshop_edit:
    path: /workshop-edit
    defaults: { _controller: HeaderBundle:Workshop:edit }

header_payment_index:
    path: /payment-index
    defaults: { _controller: HeaderBundle:Payment:index }

header_settings_index:
    path: /settings-index
    defaults: { _controller: HeaderBundle:Settings:index }

header_parameters_index:
    path: /parameters-index
    defaults: { _controller: HeaderBundle:Parameters:index }

header_measure_index:
    path: /measure-index
    defaults: { _controller: HeaderBundle:Measure:index }

header_measure_add:
    path: /measure-add
    defaults: { _controller: HeaderBundle:Measure:add }

header_measure_edit:
    path: /measure-edit
    defaults: { _controller: HeaderBundle:Measure:edit }

header_measure_remove:
    path: /measure-remove
    defaults: { _controller: HeaderBundle:Measure:remove }

header_workstation_index:
    path: /workstation-index
    defaults: { _controller: HeaderBundle:Workstation:index }

header_status_index:
    path: /status-index
    defaults: { _controller: HeaderBundle:Status:index }

header_position_index:
    path: /position-index
    defaults: { _controller: HeaderBundle:Position:index }
