services:
    # FORM TYPES
    form.type.user_edit:
        class: HeaderBundle\Form\UserEditType
        tags:
            - { name: form.type }

    form.type.change_password:
        class: HeaderBundle\Form\ChangePasswordType
        tags:
            - { name: form.type }

    form.type.workshop_add:
        class: HeaderBundle\Form\WorkshopAddType
        tags:
            - { name: form.type }

    # HELPERS
    header.helper.user.edit:
        class: HeaderBundle\Service\Helper\User\Edit
        arguments: ["@request_stack", "@doctrine.orm.default_entity_manager", "@security.token_storage", "@form.factory"]

    header.helper.password.change:
        class: HeaderBundle\Service\Helper\Password\Change
        arguments: ["@request_stack", "@form.factory", "@doctrine.orm.default_entity_manager", "@security.password_encoder", "@security.token_storage"]

    header.helper.workshop.index:
        class: HeaderBundle\Service\Helper\Workshop\Index
        arguments: ["@security.token_storage"]

    header.helper.workshop.add:
        class: HeaderBundle\Service\Helper\Workshop\Add
        arguments: ["@form.factory", "@request_stack", "@security.token_storage", "@doctrine.orm.default_entity_manager", "@app.helper.app.register"]

    header.helper.workshop.switcher:
        class: HeaderBundle\Service\Helper\Workshop\Switcher
        arguments: ["@doctrine.orm.default_entity_manager", "@request_stack", "@security.token_storage"]