services:
    # FORM TYPES
    form.type.user_edit:
        class: HeaderBundle\Form\UserEditType
        tags:
            - { name: form.type }

    form.type.change_password:
        class: HeaderBundle\Form\ChangePasswordType
        tags:
            - { name: form.type }

    form.type.workshop_add:
        class: HeaderBundle\Form\WorkshopAddType
        tags:
            - { name: form.type }

    form.type.parameters:
        class: HeaderBundle\Form\ParametersType
        tags:
            - { name: form.type }

    # HELPERS
    header.helper.user.edit:
        class: HeaderBundle\Service\Helper\User\EditHelper
        arguments: ["@request_stack", "@doctrine.orm.default_entity_manager", "@security.token_storage", "@form.factory"]

    header.helper.password.change:
        class: HeaderBundle\Service\Helper\Password\ChangeHelper
        arguments: ["@request_stack", "@form.factory", "@doctrine.orm.default_entity_manager", "@security.password_encoder", "@security.token_storage"]

    header.helper.workshop.index:
        class: HeaderBundle\Service\Helper\Workshop\IndexHelper
        arguments: ["@security.token_storage"]

    header.helper.workshop.add:
        class: HeaderBundle\Service\Helper\Workshop\AddHelper
        arguments: ["@form.factory", "@request_stack", "@security.token_storage", "@doctrine.orm.default_entity_manager", "@app.helper.app.register"]

    header.helper.workshop.switch:
        class: HeaderBundle\Service\Helper\Workshop\SwitchHelper
        arguments: ["@doctrine.orm.default_entity_manager", "@request_stack", "@security.token_storage"]

    header.helper.workshop.edit:
        class: HeaderBundle\Service\Helper\Workshop\EditHelper
        arguments: ["@request_stack", "@doctrine.orm.default_entity_manager", "@security.token_storage", "@form.factory"]

    header.helper.parameters.index:
        class: HeaderBundle\Service\Helper\Parameters\IndexHelper
        arguments: ["@request_stack", "@doctrine.orm.default_entity_manager", "@security.token_storage", "@form.factory"]

    header.helper.measure:
        class: HeaderBundle\Service\Helper\Crud\MeasureHelper
        arguments: ["@doctrine.orm.default_entity_manager", "@request_stack", "@security.token_storage"]

    header.helper.category:
        class: HeaderBundle\Service\Helper\Crud\CategoryHelper
        arguments: ["@doctrine.orm.default_entity_manager", "@request_stack", "@security.token_storage"]

    header.helper.groupp:
        class: HeaderBundle\Service\Helper\Crud\GrouppHelper
        arguments: ["@doctrine.orm.default_entity_manager", "@request_stack", "@security.token_storage"]

    header.helper.position:
        class: HeaderBundle\Service\Helper\Crud\PositionHelper
        arguments: ["@doctrine.orm.default_entity_manager", "@request_stack", "@security.token_storage"]

    header.helper.status:
        class: HeaderBundle\Service\Helper\Crud\StatusHelper
        arguments: ["@doctrine.orm.default_entity_manager", "@request_stack", "@security.token_storage"]

    header.helper.workstation:
        class: HeaderBundle\Service\Helper\Crud\WorkstationHelper
        arguments: ["@doctrine.orm.default_entity_manager", "@request_stack", "@security.token_storage"]

