header_menu:
    1:
        name: moje konto
        route: main_header_account
    2:
        name: zmiana hasła
        route: main_header_change_password
    3:
        name: mój warsztat
        route: main_header_workshop
    4:
        name: płatności
        route: main_header_payment
    5:
        name: ustawienia
        route: main_header_settings
    6:
        name: parametry
        route: main_header_parameters
    7:
        name: jednostki
        route: main_header_units
    8:
        name: stanowiska
        route: main_header_workstations
    9:
        name: statusy zleceń
        route: main_header_statuses
main_menu:
    1:
        tab: contractor
        name: klienci
        route: contractor_index
        submenu:
            1:
                name: dodaj klienta
                route: contractor_add
            2:
                name: pojazdy
                route: vehicle_index
            3:
                name: dodaj pojazd
                route: vehicle_add
    2:
        tab: order
        name: nowe zlecenie
        route: order_header_add
        submenu:
            1:
                name: zlecenia serwisowe
                route: order_header_index
    3:
        tab: warehouse
        name: towary
        route: warehouse_good_index
        submenu:
            1:
                name: przyjmij
                route: acceptance_header_add
            2:
                name: przyjęcia
                route: acceptance_header_index
            3:
                name: wystaw
                route: sale_header_add
            4:
                name: wystawienia
                route: sale_header_index
            5:
                name: producenci
                route: warehouse_producer_index
            6:
                name: kategorie
                route: warehouse_category_index
          #  7:
           #     name: katalog
            #    route: warehouse_good_catalog_index
    4:
        tab: service
        name: usługi
        route: warehouse_service_index
        submenu:
            1:
                name: czynności
                route: warehouse_action_index
    5:
        tab: bookkeeping
        name: faktury
        route: bookkeeping_index
        submenu:
            1:
                name: wystaw fakturę
                route: bookkeeping_index
            2:
                name: paragony
                route: bookkeeping_index
            3:
                name: wystaw paragon
                route: bookkeeping_index
    6:
        tab: storage
        name: przechowalnia
        route: storage_index
        submenu:
            1:
                name: przechowalnia opon
                route: storage_index
            2:
                name: miejsca
                route: storage_index
    7:
        tab: communication
        name: komunikacja
        route: communication_index
        submenu:
            1:
                name: wyślij sms
                route: communication_index
            2:
                name: wyślij e-mail
                route: communication_index
            3:
                name: sms-y wysłane
                route: communication_index
            4:
                name: e-maile wysłane
                route: communication_index
    8:
        tab: workflow
        name: zarządzanie
        route: workflow_index
        submenu:
            1:
                name: dodaj pracownika
                route: workflow_add_workman
            2:
                name: pracownicy
                route: workflow_workmen_index
            3:
                name: terminarz
                route: workflow_index
            4:
                name: kosz
                route: workflow_index