header_menu:
    1:
        name: moje konto
        route: header_user_edit
    2:
        name: zmiana hasła
        route: header_password_change
    3:
        name: moje warsztaty
        route: header_workshop_index
    4:
        name: płatności
        route: header_payment_index
    5:
        name: ustawienia
        route: header_settings_index
    6:
        name: parametry
        route: header_parameters_index
    7:
        name: jednostki
        route: header_measure_index
    8:
        name: stanowiska naprawcze
        route: header_workstation_index
    9:
        name: stanowiska pracowników
        route: header_position_index
    10:
        name: statusy zleceń
        route: header_status_index
main_menu:
    1:
        tab: customer
        name: klienci
        route: customer_index
        submenu:
            1:
                name: dodaj klienta
                route: customer_add
            2:
                name: pojazdy
                route: vehicle_index
            3:
                name: dodaj pojazd
                route: vehicle_add
    2:
        tab: order
        name: nowe zlecenie
        route: order_header_add
        submenu:
            1:
                name: zlecenia serwisowe
                route: order_header_index
    3:
        tab: warehouse
        name: towary
        route: warehouse_good_index
        submenu:
            1:
                name: przyjmij
                route: delivery_header_add
            2:
                name: przyjęcia
                route: delivery_header_index
            3:
                name: wystaw
                route: sale_header_add
            4:
                name: wystawienia
                route: sale_header_index
            5:
                name: producenci
                route: warehouse_producer_index
            6:
                name: kategorie
                route: warehouse_category_index
    4:
        tab: service
        name: usługi
        route: service_index
        submenu:
            1:
                name: czynności
                route: action_index
    5:
        tab: invoice
        name: faktury
        route: invoice_index
        submenu:
            1:
                name: wystaw fakturę
                route: invoice_add
            2:
                name: paragony
                route: bill_index
    6:
        tab: storage
        name: przechowalnia
        route: storage_general_index
        submenu:
            1:
                name: przechowalnia opon
                route: storage_tire_index
            2:
                name: miejsca
                route: storage_place_index
    7:
        tab: sms
        name: SMS
        route: sms_index
        submenu:
            1:
                name: wyślij sms
                route: sms_send
            2:
                name: wyślij e-mail
                route: email_send
            3:
                name: e-maile wysłane
                route: email_index
    8:
        tab: workflow
        name: zarządzanie
        route: workflow_index
        submenu:
            1:
                name: dodaj pracownika
                route: workflow_workman_add
            2:
                name: pracownicy
                route: workflow_workman_index
            3:
                name: terminarz
                route: workflow_schedule_index
            4:
                name: kosz
                route: trash_index