services:
# SECURITY
    app.security.user_authenticator:
        class: AppBundle\Service\Security\UserAuthenticator
        arguments: ["@security.password_encoder", "@doctrine.orm.default_entity_manager"]

# FORM TYPES
    form.type.province:
        class: AppBundle\Form\ProvinceType
        tags:
            - { name: form.type }

    form.type.address:
        class: AppBundle\Form\AddressType
        tags:
            - { name: form.type }

    form.type.user:
        class: AppBundle\Form\UserType
        tags:
            - { name: form.type }

    form.type.workshop:
        class: AppBundle\Form\WorkshopType
        tags:
            - { name: form.type }

    form.type.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type }

    form.type.login:
        class: AppBundle\Form\LoginType
        tags:
            - { name: form.type }

# COMMANDS
    app.command.generate_provinces:
        class: AppBundle\Command\GenerateProvinces
        arguments: ["@service_container"]
        tags:
            - { name: console.command }

    app.command.updated-at:
        class: AppBundle\Command\UpdatedAt
        arguments: ["@service_container"]
        tags:
            - { name: console.command }

# VALIDATORS
    app.validator.mobile_phone:
        class: AppBundle\Form\Validator\MobilePhoneValidator
        arguments: ["@service_container"]
        tags:
            - { name: validator.constraint_validator }

    app.validator.email:
            class: AppBundle\Form\Validator\EmailValidator
            arguments: ["@doctrine.orm.entity_manager"]
            tags:
                - { name: validator.constraint_validator }

# HELPERS
    app.helper.yaml_parser:
        class: AppBundle\Service\Helper\YamlParser