services:
# SECURITY
    app.security.user_authenticator:
        class: AppBundle\Service\Security\UserAuthenticator
        arguments: ["@security.password_encoder", "@doctrine.orm.default_entity_manager"]

# FORM TYPES
    form.type.address:
        class: AppBundle\Form\AddressType
        tags:
            - { name: form.type }

    form.type.user:
        class: AppBundle\Form\UserType
        tags:
            - { name: form.type }

    form.type.workshop:
        class: AppBundle\Form\WorkshopType
        tags:
            - { name: form.type }

    form.type.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type }

    form.type.login:
        class: AppBundle\Form\LoginType
        tags:
            - { name: form.type }

# COMMANDS
    app.command.generate_provinces:
        class: AppBundle\Command\GenerateProvinces
        arguments: ['@doctrine.orm.default_entity_manager', '@service_container']

    app.command.updated-at:
        class: AppBundle\Command\UpdatedAt
        arguments: ["@doctrine.orm.default_entity_manager", "@app.yaml_parser"]
        tags:
            - { name: console.command }

    app.command.truncate_all_tables:
        class: AppBundle\Command\TruncateAllTables
        arguments: ["@doctrine.orm.default_entity_manager", "@app.yaml_parser"]
        tags:
            - { name: console.command }

    app.command.delete_all_tables:
        class: AppBundle\Command\DeleteAllTables
        arguments: ["@doctrine.orm.default_entity_manager", "@app.yaml_parser"]
        tags:
            - { name: console.command }

# VALIDATORS
    app.validator.mobile_phone:
        class: AppBundle\Form\Validator\MobilePhoneValidator
        tags:
            - { name: validator.constraint_validator }

    app.validator.email:
        class: AppBundle\Form\Validator\EmailValidator
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: validator.constraint_validator }

    app.validator.password:
        class: AppBundle\Form\Validator\PasswordValidator
        tags:
            - { name: validator.constraint_validator }

    app.validator.nip:
        class: AppBundle\Form\Validator\NipValidator
        tags:
            - { name: validator.constraint_validator }

    app.validator.nrb:
        class: AppBundle\Form\Validator\NrbValidator
        tags:
            - { name: validator.constraint_validator }

    app.validator.pesel:
        class: AppBundle\Form\Validator\PeselValidator
        tags:
            - { name: validator.constraint_validator }

    app.validator.post_code:
        class: AppBundle\Form\Validator\PostCodeValidator
        tags:
            - { name: validator.constraint_validator }

# HELPERS
    app.helper.app.register:
        class: AppBundle\Service\Helper\App\Register
        arguments: ["@doctrine.orm.default_entity_manager", "@security.password_encoder", "@service_container"]

# OTHER
    app.yaml_parser:
        class: AppBundle\Service\YamlParser

