vehicle_index:
    path: /pojazdy
    defaults: { _controller: VehicleBundle:Vehicle:index }

vehicle_add:
    path: /dodaj-pojazd
    defaults: { _controller: VehicleBundle:Vehicle:add }

vehicle_show:
    path: /pojazdy/{vehicleId}
    defaults: { _controller: VehicleBundle:Vehicle:show }

vehicle_edit:
    path: /edytuj-pojazd/{vehicleId}
    defaults: { _controller: VehicleBundle:Vehicle:edit }

vehicle_remove:
    path: /usun-pojazd
    defaults: { _controller: VehicleBundle:Vehicle:remove }

vehicle_retrieve:
    path: /vehicle-retrieve
    defaults: { _controller: VehicleBundle:Vehicle:retrieve }

vehicle_retrieve_brands:
    path: /vehicle/retrieve-brands
    defaults: { _controller: VehicleBundle:Vehicle:retrieveBrands }

vehicle_retrieve_models:
    path: /vehicle/retrieve-models
    defaults: { _controller: VehicleBundle:Vehicle:retrieveModels }