services:
# FORM TYPES
    form.type.vehicle:
        class: VehicleBundle\Form\VehicleType
        arguments: ["@doctrine.orm.default_entity_manager", "@security.token_storage"]
        tags:
            - { name: form.type}

# VALIDATORS
    app.validator.engine_displacement:
        class: VehicleBundle\Form\Validator\EngineDisplacementValidator
        tags:
            - { name: validator.constraint_validator }

# HELPERS
    vehicle.helper.add:
        class: VehicleBundle\Service\Helper\VehicleAddHelper
        arguments: ["@request_stack", "@security.token_storage", "@form.factory", "@doctrine.orm.default_entity_manager", "@service_container", "@header.helper.car_brand", "@header.helper.car_model", "@app.trade"]

    vehicle.helper.index:
        class: VehicleBundle\Service\Helper\VehicleIndexHelper
        arguments: ["@request_stack", "@security.token_storage", "@form.factory", "@doctrine.orm.default_entity_manager", "@service_container"]