service_index:
    path: /uslugi
    defaults: { _controller: ServiceBundle:Service:index }

action_index:
    path: /czynnosci
    defaults: { _controller: ServiceBundle:Action:index }

action_add:
    path: /action-add
    defaults: { _controller: ServiceBundle:Action:add }

action_edit:
    path: /action-edit
    defaults: { _controller: ServiceBundle:Action:edit }

action_remove:
    path: /action-remove
    defaults: { _controller: ServiceBundle:Action:remove }
