sale_index:
    path: /wystawienia-towarow
    defaults: { _controller: SaleBundle:Sale:index }

sale_show:
    path: /wystawienia-towarow/{saleHeaderId}
    defaults: { _controller: SaleBundle:Sale:show }

sale_header_add:
    path: /wystaw-towar
    defaults: { _controller: SaleBundle:SaleHeader:add }

sale_header_retrieve_customers:
    path: /sale/retrieve-customers
    defaults: { _controller: SaleBundle:SaleHeader:retrieveCustomers }

sale_header_get_next_number:
    path: /sale/get-next-number
    defaults: { _controller: SaleBundle:SaleHeader:getNextDocumentNumber }
