# SALE
sale_index:
    path: /wystawienia-towarow
    defaults: { _controller: SaleBundle:Sale:index }

sale_retrieve:
    path: /sale-retrieve
    defaults: { _controller: SaleBundle:Sale:retrieve }
    
sale_show:
    path: /wystawienia-towarow/{saleHeaderId}
    defaults: { _controller: SaleBundle:Sale:show }

# HEADER
sale_header_add:
    path: /wystaw-towar
    defaults: { _controller: SaleBundle:SaleHeader:add }

sale_header_retrieve_customers:
    path: /sale/retrieve-customers
    defaults: { _controller: SaleBundle:SaleHeader:retrieveCustomers }

sale_header_get_next_number:
    path: /sale/get-next-number
    defaults: { _controller: SaleBundle:SaleHeader:getNextDocumentNumber }

# DETAIL
sale_detail_add:
    path: /wystawienia-towarow/{saleHeaderId}/dodaj-pozycje
    defaults: { _controller: SaleBundle:SaleDetail:add }

sale_retrieve_goods:
    path: /sale/retrieve-goods
    defaults: { _controller: SaleBundle:SaleDetail:retrieveGoods }

sale_retrieve_indexxes:
    path: /sale/retrieve-indexxes
    defaults: { _controller: SaleBundle:SaleDetail:retrieveIndexxes }