AppBundle\Entity\SaleHeader:
    properties:
        document_type:
            - Choice:
                choices: ['wydanie z magazynu', 'asygnata']
                message: 'Wybrano nieprawidłowy typ dokumentu'
                groups: [ sale_header_add ]
        document_number:
            - Length:
                max: 100
                maxMessage: 'Numer dokumentu nie powinien być dłuższy niż 100 znaków'
                groups: [ sale_header_add ]
        remarks:
            - Length:
                max: 255
                maxMessage: 'Pole Uwagi powinno zawierać maksymalnie 255 znaków'
                groups: [ sale_header_add ]
        total_net_before_discount:
            - Length:
                max: 10
                maxMessage: 'To pole może zawierać maksymalnie 10 znaków'
                groups: [ sale_header_add ]
            - AppBundle\Form\Validator\Constraint\Trade:
                groups: [ sale_header_add ]
        discount:
            - Length:
                max: 10
                maxMessage: 'To pole może zawierać maksymalnie 10 znaków'
                groups: [ sale_header_add ]
            - AppBundle\Form\Validator\Constraint\Trade:
                groups: [ sale_header_add ]
        total_net:
            - Length:
                max: 10
                maxMessage: 'To pole może zawierać maksymalnie 10 znaków'
                groups: [ sale_header_add ]
            - AppBundle\Form\Validator\Constraint\Trade:
                groups: [ sale_header_add ]
        vat:
            - Length:
                max: 10
                maxMessage: 'To pole może zawierać maksymalnie 10 znaków'
                groups: [ sale_header_add ]
            - AppBundle\Form\Validator\Constraint\Trade:
                groups: [ sale_header_add ]
        total_due:
            - Length:
                max: 10
                maxMessage: 'To pole może zawierać maksymalnie 10 znaków'
                groups: [ sale_header_add ]
            - AppBundle\Form\Validator\Constraint\Trade:
                groups: [ sale_header_add ]
AppBundle\Entity\SaleDetail:
    properties:
        remarks:
            - Length:
                max: 255
                maxMessage: 'Pole Uwagi powinno zawierać maksymalnie 255 znaków'
                groups: [ sale_detail_add ]
        unit_price_net:
            - Length:
                max: 10
                maxMessage: 'To pole może zawierać maksymalnie 10 znaków'
                groups: [ sale_detail_add ]
            - AppBundle\Form\Validator\Constraint\Trade:
                groups: [ sale_detail_add ]
        quantity:
            - Length:
                max: 10
                maxMessage: 'To pole może zawierać maksymalnie 10 znaków'
                groups: [ sale_detail_add ]
            - AppBundle\Form\Validator\Constraint\Trade:
                groups: [ sale_detail_add ]
        total_net_before_discount:
            - Length:
                max: 10
                maxMessage: 'To pole może zawierać maksymalnie 10 znaków'
                groups: [ sale_detail_add ]
            - AppBundle\Form\Validator\Constraint\Trade:
                groups: [ sale_detail_add ]
        discount_pc:
            - Range:
                min: 0
                max: 100
                minMessage: 'Wartości procentowe muszą mieścić między 0 a 100'
                maxMessage: 'Wartości procentowe muszą mieścić między 0 a 100'
                groups: [ sale_detail_add ]
        discount:
            - Length:
                max: 10
                maxMessage: 'To pole może zawierać maksymalnie 10 znaków'
                groups: [ sale_detail_add ]
            - AppBundle\Form\Validator\Constraint\Trade:
                groups: [ sale_detail_add ]
        total_net:
            - Length:
                max: 10
                maxMessage: 'To pole może zawierać maksymalnie 10 znaków'
                groups: [ sale_detail_add ]
            - AppBundle\Form\Validator\Constraint\Trade:
                groups: [ sale_detail_add ]
        vat_pc:
            - Range:
                min: 0
                max: 100
                minMessage: 'Wartości procentowe muszą mieścić między 0 a 100'
                maxMessage: 'Wartości procentowe muszą mieścić między 0 a 100'
                groups: [ sale_detail_add ]
        vat:
            - Length:
                max: 10
                maxMessage: 'To pole może zawierać maksymalnie 10 znaków'
                groups: [ sale_detail_add ]
            - AppBundle\Form\Validator\Constraint\Trade:
                groups: [ sale_detail_add ]
        total_due:
            - Length:
                max: 10
                maxMessage: 'To pole może zawierać maksymalnie 10 znaków'
                groups: [ sale_detail_add ]
            - AppBundle\Form\Validator\Constraint\Trade:
                groups: [ sale_detail_add ]