AppBundle\Entity\Indexx:
    type: entity
    table: indexx
    repositoryClass: AppBundle\Entity\Repository\IndexxRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        good_id:
            type: integer
            nullable: false
            options:
                unsigned: true
        producer_id:
            type: integer
            nullable: false
            options:
                unsigned: true
        name:
            type: string
            length: 30
            nullable: false
            options:
                fixed: false
        quantity:
            type: decimal
            nullable: false
            precision: 8
            scale: 2
            options:
                unsigned: true
                default: 0.00
        unit_price_net:
            type: decimal
            nullable: true
            precision: 8
            scale: 2
            options:
                unsigned: true
        created_at:
            type: datetime
            nullable: false
        updated_at:
            type: datetime
            nullable: false
        removed_at:
            type: datetime
            nullable: true
        deleted_at:
            type: datetime
            nullable: true
        created_by_id:
            type: integer
            nullable: true
            options:
                unsigned: true
        updated_by_id:
            type: integer
            nullable: true
            options:
                unsigned: true
        removed_by_id:
            type: integer
            nullable: true
            options:
                unsigned: true
        deleted_by_id:
            type: integer
            nullable: true
            options:
                unsigned: true
    manyToOne:
        good:
            targetEntity: Good
            joinColumn:
                name: good_id
                referencedColumnName: id
            inversedBy: indexxes
            cascade: [persist]
        producer:
            targetEntity: Producer
            joinColumn:
                name: producer_id
                referencedColumnName: id
        created_by:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: created_by_id
                referencedColumnName: id
        updated_by:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: updated_by_id
                referencedColumnName: id
        removed_by:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: removed_by_id
                referencedColumnName: id
        deleted_by:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: deleted_by_id
                referencedColumnName: id
    uniqueConstraints:
        good_name:
            columns: [ good_id, name, producer_id ]