AppBundle\Entity\Service:
    type: entity
    table: service
    repositoryClass: AppBundle\Entity\Repository\ServiceRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        workshop_id:
            type: integer
            nullable: false
            options:
                unsigned: true
        measure_id:
            type: integer
            length: 10
            nullable: true
            options:
                unsigned: true
        name:
            type: string
            length: 50
            nullable: false
            options:
                fixed: false
        unit_price_net:
            type: decimal
            nullable: true
            precision: 8
            scale: 2
            options:
                unsigned: true
        remarks:
            type: string
            length: 255
            nullable: true
            options:
                fixed: false
        created_at:
            type: datetime
            nullable: false
        updated_at:
            type: datetime
            nullable: false
        removed_at:
            type: datetime
            nullable: true
        deleted_at:
            type: datetime
            nullable: true
        created_by_id:
            type: integer
            nullable: true
            options:
                unsigned: true
        updated_by_id:
            type: integer
            nullable: true
            options:
                unsigned: true
        removed_by_id:
            type: integer
            nullable: true
            options:
                unsigned: true
        deleted_by_id:
            type: integer
            nullable: true
            options:
                unsigned: true
    manyToOne:
        workshop:
            targetEntity: Workshop
            joinColumn:
                name: workshop_id
                referencedColumnName: id
        measure:
            targetEntity: Measure
            joinColumn:
                name: measure_id
                referencedColumnName: id
        created_by:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: created_by_id
                referencedColumnName: id
        updated_by:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: updated_by_id
                referencedColumnName: id
        removed_by:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: removed_by_id
                referencedColumnName: id
        deleted_by:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: deleted_by_id
                referencedColumnName: id