AppBundle\Entity\Status:
    type: entity
    table: status
    repositoryClass: AppBundle\Entity\Repository\StatusRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        workshop_id:
            type: integer
            nullable: false
            options:
                unsigned: true
        name:
            type: string
            length: 25
            nullable: false
            options:
                fixed: false
        hex_color:
            type: string
            length: 7
            nullable: true
            options:
                fixed: true
        created_at:
            type: datetime
            nullable: false
        updated_at:
            type: datetime
            nullable: false
        removed_at:
            type: datetime
            nullable: true
        deleted_at:
            type: datetime
            nullable: true
        created_by_id:
            type: integer
            nullable: true
            options:
                unsigned: true
        updated_by_id:
            type: integer
            nullable: true
            options:
                unsigned: true
        removed_by_id:
            type: integer
            nullable: true
            options:
                unsigned: true
        deleted_by_id:
            type: integer
            nullable: true
            options:
                unsigned: true
    manyToOne:
        workshop:
            targetEntity: Workshop
            joinColumn:
                name: workshop_id
                referencedColumnName: id
        created_by:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: created_by_id
                referencedColumnName: id
        updated_by:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: updated_by_id
                referencedColumnName: id
        removed_by:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: removed_by_id
                referencedColumnName: id
        deleted_by:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: deleted_by_id
                referencedColumnName: id
    manyToMany:
        order_headers:
            targetEntity: AppBundle\Entity\OrderHeader
            mappedBy: statuses
        order_indexxes:
            targetEntity: AppBundle\Entity\OrderIndexx
            mappedBy: statuses
        order_services:
            targetEntity: AppBundle\Entity\OrderService
            mappedBy: statuses
        order_actions:
            targetEntity: AppBundle\Entity\OrderAction
            mappedBy: statuses
    uniqueConstraints:
        workshop_name:
            columns: [ workshop_id, name ]