AppBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: AppBundle\Entity\Repository\UserRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        current_workshop_id:
            type: integer
            nullable: true
            options:
                unsigned: true
        forename:
            type: string
            length: 30
            nullable: false
        surname:
            type: string
            length: 50
            nullable: false
        password:
            type: string
            length: 60
            nullable: false
            options:
                fixed: true
        status:
            type: smallint
            length: 1
            nullable: false
            options:
                default: 1
                comment: '0 - użytkownik zweryfikował się negatywnie przez e-mail, 1 - użytkownik jeszcze się nie weryfikował, 2 - użytkownik zweryfikował się pozytywnie, 3 - użytkownik zbanowany przez nas'
        hourly_rate_net:
            type: decimal
            nullable: true
            precision: 5
            scale: 2
            options:
                unsigned: true
                comment: "Stawka netto na godzinę"
        phone1:
            type: string
            length: 12
            nullable: true
            options:
                fixed: true
        phone2:
            type: string
            length: 12
            nullable: true
            options:
                fixed: true
        email:
            type: string
            length: 80
            nullable: false
        address_id:
            type: integer
            nullable: true
            options:
                unsigned: true
        nip:
            type: string
            length: 10
            nullable: true
            options:
                fixed: true
        pesel:
            type: string
            length: 11
            nullable: true
            options:
                fixed: true
        bank_account_number:
            type: string
            length: 26
            nullable: true
            options:
                fixed: false
        remarks:
            type: string
            length: 255
            nullable: true
            options:
                fixed: false
        created_at:
            type: datetime
            nullable: false
        updated_at:
            type: datetime
            nullable: false
        removed_at:
            type: datetime
            nullable: true
        deleted_at:
            type: datetime
            nullable: true
        created_by_id:
            type: integer
            nullable: true
            options:
                unsigned: true
        updated_by_id:
            type: integer
            nullable: true
            options:
                unsigned: true
        removed_by_id:
            type: integer
            nullable: true
            options:
                unsigned: true
        deleted_by_id:
            type: integer
            nullable: true
            options:
                unsigned: true
    oneToOne:
        address:
            targetEntity: Address
            inversedBy: user
            joinColumn:
                name: address_id
                referencedColumnName: id
            cascade: [persist]
    oneToMany:
        roles:
            targetEntity: UserRole
            mappedBy: user
    manyToMany:
        workshops:
            targetEntity: Workshop
            inversedBy: users
            joinTable:
                name: user_workshop
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                  workshop_id:
                    referencedColumnName: id
        order_services:
            targetEntity: OrderService
            mappedBy: workmans
        order_actions:
            targetEntity: OrderAction
            mappedBy: workmans
        positions:
            targetEntity: AppBundle\Entity\Position
            inversedBy: workmans
            joinTable:
                name: workman_position
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    position_id:
                        referencedColumnName: id
    manyToOne:
        current_workshop:
            targetEntity: Workshop
            joinColumn:
                name: current_workshop_id
                referencedColumnName: id
        created_by:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: created_by_id
                referencedColumnName: id
        updated_by:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: updated_by_id
                referencedColumnName: id
        removed_by:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: removed_by_id
                referencedColumnName: id
        deleted_by:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: deleted_by_id
                referencedColumnName: id