AppBundle\Entity\Workshop:
    type: entity
    table: workshop
    repositoryClass: AppBundle\Entity\Repository\WorkshopRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        admin_user_id:
            type: integer
            nullable: false
            options:
                unsigned: true
        name:
            type: string
            length: 80
            nullable: false
            options:
                fixed: false
        phone:
            type: string
            length: 12
            nullable: true
            options:
                fixed: true
        email:
            type: string
            length: 80
            nullable: true
            options:
                fixed: false
        subscription_expiration_date:
            type: datetime
            nullable: true
        address_id:
            type: integer
            nullable: true
            options:
                unsigned: true
        nip:
            type: string
            length: 10
            nullable: true
            options:
                fixed: true
        bank_account_number:
            type: string
            length: 26
            nullable: true
            options:
                fixed: false
        website_url:
            type: string
            length: 50
            nullable: true
            options:
                fixed: false
        created_at:
            type: datetime
            nullable: false
        updated_at:
            type: datetime
            nullable: false
        removed_at:
            type: datetime
            nullable: true
        deleted_at:
            type: datetime
            nullable: true
        created_by_id:
            type: integer
            nullable: true
            options:
                unsigned: true
        updated_by_id:
            type: integer
            nullable: true
            options:
                unsigned: true
        removed_by_id:
            type: integer
            nullable: true
            options:
                unsigned: true
        deleted_by_id:
            type: integer
            nullable: true
            options:
                unsigned: true
    oneToOne:
        parameters:
            targetEntity: Parameters
            mappedBy: workshop
        settings:
            targetEntity: Settings
            mappedBy: workshop
        address:
            targetEntity: Address
            inversedBy: workshop
            joinColumn:
                name: address_id
                referencedColumnName: id
    manyToMany:
        users:
            targetEntity: User
            mappedBy: workshops
    manyToOne:
        admin:
            targetEntity: User
            joinColumn:
                name: admin_user_id
                referencedColumnName: id
        created_by:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: created_by_id
                referencedColumnName: id
        updated_by:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: updated_by_id
                referencedColumnName: id
        removed_by:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: removed_by_id
                referencedColumnName: id
        deleted_by:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: deleted_by_id
                referencedColumnName: id
    oneToMany:
        workstations:
            targetEntity: AppBundle\Entity\Workstation
            mappedBy: workshop
        models:
            targetEntity: Model
            mappedBy: workshop
        vehicles:
            targetEntity: Vehicle
            mappedBy: workshop
        customers:
            targetEntity: Customer
            mappedBy: workshop
        goods:
            targetEntity: Good
            mappedBy: workshop
        measures:
            targetEntity: Measure
            mappedBy: workshop