customer_index:
    path: /klienci
    defaults: { _controller: CustomerBundle:Customer:index }

customer_index_send_event:
    path: /customer-index/send-event
    defaults: { _controller: CustomerBundle:Customer:sendEvent }

customer_retrieve:
    path: /customer-retrieve
    defaults: { _controller: CustomerBundle:Customer:retrieve }

customer_get_one:
    path: /customer/get-one/{hydrationMode}
    defaults: { _controller: CustomerBundle:Customer:getOne }

customer_show:
    path: /klienci/{customerId}
    defaults: { _controller: CustomerBundle:Customer:show }

customer_add:
    path: /dodaj-klienta
    defaults: { _controller: CustomerBundle:Customer:add }

customer_edit:
    path: /edytuj-klienta/{customerId}
    defaults: { _controller: CustomerBundle:Customer:edit }

customer_remove:
    path: /usun-klienta
    defaults: { _controller: CustomerBundle:Customer:remove }
