services:
# FORM TYPES
    form.type.customer:
        class: CustomerBundle\Form\CustomerType

# HELPERS
    customer.helper.add:
        class: CustomerBundle\Service\Helper\CustomerAddHelper
        arguments: ["@request_stack", "@security.token_storage", "@form.factory", "@doctrine.orm.default_entity_manager", "@service_container"]

    customer.helper.index:
        class: CustomerBundle\Service\Helper\CustomerIndexHelper
        arguments: ["@request_stack", "@security.token_storage", "@form.factory", "@doctrine.orm.default_entity_manager", "@service_container"]