services:
# FORM TYPES
    form.type.customer:
        class: CustomerBundle\Form\CustomerType
        arguments: ["@doctrine.orm.default_entity_manager", "@security.token_storage"]
        tags:
            - { name: form.type}

    form.type.groupp:
        class: CustomerBundle\Form\GrouppType
        tags:
            - { name: form.type}

# HELPERS
    customer.helper.add:
        class: CustomerBundle\Service\Helper\CustomerAddHelper
        arguments: ["@request_stack", "@security.token_storage", "@form.factory", "@doctrine.orm.default_entity_manager", "@service_container"]

    customer.helper.index:
        class: CustomerBundle\Service\Helper\CustomerIndexHelper
        arguments: ["@request_stack", "@security.token_storage", "@form.factory", "@doctrine.orm.default_entity_manager", "@service_container", "@email.mailer"]

    customer.helper.show:
        class: CustomerBundle\Service\Helper\CustomerShowHelper
        arguments: ["@request_stack", "@security.token_storage", "@form.factory", "@doctrine.orm.default_entity_manager"]

