AppBundle\Entity\Customer:
    properties:
        forename:
            - NotBlank:
                message: 'Pole Imię nie może być puste'
                groups: [ customer ]
            - Length:
                min: 2
                max: 30
                minMessage: 'Pole Imię powinno zawierać co najmniej 2 litery'
                maxMessage: 'Pole Imię może zawierać maksymalnie 30 liter'
                groups: [ customer ]
        surname:
            - NotBlank:
                message: 'Pole Nazwisko nie może być puste'
                groups: [ customer ]
            - Length:
                min: 2
                max: 50
                minMessage: 'Pole Nazwisko powinno zawierać co najmniej 2 litery'
                maxMessage: 'Pole Nazwisko może zawierać maksymalnie 50 liter'
                groups: [ customer ]
        mobile_phone1:
            - Length:
                max: 15
                maxMessage: 'Pole Telefon kom. 1 może zawierać maksymalnie 15 liter'
                groups: [ customer ]
            - Regex:
                pattern: '/^\+{1}[0-9]{11}$/'
                match: true
                message: 'Wpisany numer telefonu jest nieprawidłowy'
                groups: [ customer ]
        mobile_phone2:
            - Length:
                max: 15
                maxMessage: 'Pole Telefon kom. 2 może zawierać maksymalnie 15 liter'
                groups: [ customer ]
            - Regex:
                pattern: '/^\+{1}[0-9]{11}$/'
                match: true
                message: 'Wpisany numer telefonu jest nieprawidłowy'
                groups: [ customer ]
        email:
            - Regex:
                pattern: '/^[a-zA-Z]+[a-zA-Z0-9\.\-_]{1,32}\@[a-zA-Z0-9\.\-_]+\.[a-z]{2,4}$/D'
                message: 'Adres e-mail powinien być wpisany w formacie: nazwa@domena.pl'
                match: true
                groups: [ customer ]
            - Length:
                min: 6
                max: 80
                minMessage: 'Pole E-mail powinno zawierać co najmniej 6 znaków'
                maxMessage: 'Pole E-mail może zawierać maksymalnie 80 znaków'
                groups: [ customer ]
        nip:
            - AppBundle\Form\Validator\Constraint\Nip:
                groups: [ customer ]
        pesel:
            - AppBundle\Form\Validator\Constraint\Pesel:
                groups: [ customer ]
        bank_account_number:
            - AppBundle\Form\Validator\Constraint\Nrb:
                groups: [ customer ]
        address:
            - Valid: ~