order_index:
    path: /zlecenia-serwisowe
    defaults: { _controller: OrderBundle:Order:index }
    
order_retrieve:
    path: /order-retrieve
    defaults: { _controller: OrderBundle:Order:retrieve }

order_show:
    path: /zlecenia-serwisowe/{orderHeaderId}
    defaults: { _controller: OrderBundle:Order:show }

order_header_add:
    path: /nowe-zlecenie
    defaults: { _controller: OrderBundle:OrderHeader:add }

order_header_retrieve_customers:
    path: /order/retrieve-customers
    defaults: { _controller: OrderBundle:OrderHeader:retrieveCustomers }

order_header_retrieve_vehicles:
    path: /order/retrieve-vehicles
    defaults: { _controller: OrderBundle:OrderHeader:retrieveVehicles }

order_header_retrieve_symptoms:
    path: /order/retrieve-symptoms
    defaults: { _controller: OrderBundle:OrderHeader:retrieveSymptoms }



