AppBundle\Entity\OrderIndexx:
    properties:
        remarks:
            - Length:
                max: 255
                maxMessage: 'Pole Uwagi powinno zawierać maksymalnie 255 znaków'
                groups: [ order_indexx_add ]
        unit_price_net:
            - Length:
                max: 10
                maxMessage: 'To pole może zawierać maksymalnie 10 znaków'
                groups: [ order_indexx_add ]
            - AppBundle\Form\Validator\Constraint\Trade:
                groups: [ order_indexx_add ]
        quantity:
            - Length:
                max: 10
                maxMessage: 'To pole może zawierać maksymalnie 10 znaków'
                groups: [ order_indexx_add ]
            - AppBundle\Form\Validator\Constraint\Trade:
                groups: [ order_indexx_add ]
        total_net_before_discount:
            - Length:
                max: 10
                maxMessage: 'To pole może zawierać maksymalnie 10 znaków'
                groups: [ order_indexx_add ]
            - AppBundle\Form\Validator\Constraint\Trade:
                groups: [ order_indexx_add ]
        discount_pc:
            - Range:
                min: 0
                max: 100
                minMessage: 'Wartości procentowe muszą mieścić między 0 a 100'
                maxMessage: 'Wartości procentowe muszą mieścić między 0 a 100'
                groups: [ order_indexx_add ]
        discount:
            - Length:
                max: 10
                maxMessage: 'To pole może zawierać maksymalnie 10 znaków'
                groups: [ order_indexx_add ]
            - AppBundle\Form\Validator\Constraint\Trade:
                groups: [ order_indexx_add ]
        total_net:
            - Length:
                max: 10
                maxMessage: 'To pole może zawierać maksymalnie 10 znaków'
                groups: [ order_indexx_add ]
            - AppBundle\Form\Validator\Constraint\Trade:
                groups: [ order_indexx_add ]
        vat_pc:
            - Range:
                min: 0
                max: 100
                minMessage: 'Wartości procentowe muszą mieścić między 0 a 100'
                maxMessage: 'Wartości procentowe muszą mieścić między 0 a 100'
                groups: [ order_indexx_add ]
        vat:
            - Length:
                max: 10
                maxMessage: 'To pole może zawierać maksymalnie 10 znaków'
                groups: [ order_indexx_add ]
            - AppBundle\Form\Validator\Constraint\Trade:
                groups: [ order_indexx_add ]
        total_due:
            - Length:
                max: 10
                maxMessage: 'To pole może zawierać maksymalnie 10 znaków'
                groups: [ order_indexx_add ]
            - AppBundle\Form\Validator\Constraint\Trade:
                groups: [ order_indexx_add ]