workflow_index:
    path: /zarzadzanie
    defaults: { _controller: WorkflowBundle:Workflow:index }

workflow_workman_index:
    path: /pracownicy
    defaults: { _controller: WorkflowBundle:Workman:index }

workflow_workman_add:
    path: /dodaj-pracownika
    defaults: { _controller: WorkflowBundle:Workman:add }

workflow_schedule_index:
    path: /terminarz
    defaults: { _controller: WorkflowBundle:Schedule:index }